{
    "openapi": "3.0.0",
    "info": {
        "title": "Simple Parking Booking",
        "description": "API Documentation",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "/api"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Authentication Login",
                "operationId": "AuthLogin",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "properties": {
                                        "email": {
                                            "type": "string"
                                        },
                                        "password": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                }
                            },
                            "example": {
                                "email": "demo@parking.id",
                                "password": "pass123"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "user": {
                                            "type": "array",
                                            "items": {
                                                "properties": {
                                                    "id": {
                                                        "type": "integer"
                                                    },
                                                    "name": {
                                                        "type": "string"
                                                    },
                                                    "email": {
                                                        "type": "string"
                                                    },
                                                    "email_verified_at": {
                                                        "type": "string"
                                                    },
                                                    "created_at": {
                                                        "type": "datetime"
                                                    },
                                                    "updated_at": {
                                                        "type": "datetime"
                                                    }
                                                },
                                                "type": "object"
                                            },
                                            "example": {
                                                "id": 1,
                                                "name": "demo",
                                                "email": "demo@parking.id",
                                                "email_verified_at": null,
                                                "created_at": "2021-11-18T12:52:12.000000Z",
                                                "updated_at": "2021-11-18T12:52:12.000000Z"
                                            }
                                        },
                                        "message": {
                                            "title": "message",
                                            "description": "Success",
                                            "format": "string",
                                            "default": "Success"
                                        },
                                        "token": {
                                            "title": "token",
                                            "description": "token",
                                            "format": "string",
                                            "default": "7|p2E0XEiTJBh07vcFgjAvZeQ71msi2qD2NZFEIBsl"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Authentication Register",
                "operationId": "AuthRegister",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "password": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                }
                            },
                            "example": {
                                "name": "demo",
                                "email": "demo@parking.id",
                                "password": "pass123"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "user": {
                                            "type": "array",
                                            "items": {
                                                "properties": {
                                                    "id": {
                                                        "type": "integer"
                                                    },
                                                    "name": {
                                                        "type": "string"
                                                    },
                                                    "email": {
                                                        "type": "string"
                                                    },
                                                    "created_at": {
                                                        "type": "datetime"
                                                    },
                                                    "updated_at": {
                                                        "type": "datetime"
                                                    }
                                                },
                                                "type": "object"
                                            },
                                            "example": {
                                                "id": 1,
                                                "name": "demo",
                                                "email": "demo@parking.id",
                                                "created_at": "2021-11-18T12:52:12.000000Z",
                                                "updated_at": "2021-11-18T12:52:12.000000Z"
                                            }
                                        },
                                        "message": {
                                            "title": "message",
                                            "description": "Success",
                                            "format": "string",
                                            "default": "New user created"
                                        },
                                        "token": {
                                            "title": "token",
                                            "description": "token",
                                            "format": "string",
                                            "default": "7|p2E0XEiTJBh07vcFgjAvZeQ71msi2qD2NZFEIBsl"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/booking": {
            "get": {
                "tags": [
                    "Booking"
                ],
                "summary": "Get Booking List",
                "operationId": "bookingList",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BookingViewResource"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Booking"
                ],
                "summary": "Booking Created",
                "operationId": "bookingCreated",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "properties": {
                                        "bay_id": {
                                            "type": "integer"
                                        },
                                        "carnumber": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                }
                            },
                            "example": {
                                "bay_id": 1,
                                "carnumber": "L181KL"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BookingResource"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/booking-available": {
            "get": {
                "tags": [
                    "Booking"
                ],
                "summary": "Get Booking Available List",
                "operationId": "bookingAvailable",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string",
                                            "example": "Balance occupied"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "properties": {
                                                    "bayname": {
                                                        "type": "string",
                                                        "example": ""
                                                    },
                                                    "balance": {
                                                        "type": "integer",
                                                        "example": ""
                                                    }
                                                },
                                                "type": "object"
                                            },
                                            "example": [
                                                {
                                                    "bayname": "A",
                                                    "balance": 1
                                                },
                                                {
                                                    "bayname": "B",
                                                    "balance": 1
                                                },
                                                {
                                                    "bayname": "C",
                                                    "balance": 1
                                                }
                                            ]
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/booking/{car_number}": {
            "put": {
                "tags": [
                    "Booking"
                ],
                "summary": "Booking Updated",
                "operationId": "bookingUpdated",
                "parameters": [
                    {
                        "name": "car_number",
                        "in": "path",
                        "description": "car number",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string",
                                            "example": "Available for booking"
                                        },
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "properties": {
                                                    "id": {
                                                        "type": "integer",
                                                        "example": ""
                                                    },
                                                    "bay_id": {
                                                        "type": "integer",
                                                        "example": ""
                                                    },
                                                    "price_id": {
                                                        "type": "integer",
                                                        "example": ""
                                                    },
                                                    "carnumber": {
                                                        "type": "string",
                                                        "example": ""
                                                    },
                                                    "startsession": {
                                                        "type": "datetime",
                                                        "example": ""
                                                    },
                                                    "endsession": {
                                                        "type": "datetime",
                                                        "example": ""
                                                    },
                                                    "occupied": {
                                                        "type": "boolean",
                                                        "example": ""
                                                    },
                                                    "created_at": {
                                                        "type": "datetime",
                                                        "example": ""
                                                    },
                                                    "updated_at": {
                                                        "type": "datetime",
                                                        "example": ""
                                                    }
                                                },
                                                "type": "object"
                                            },
                                            "example": {
                                                "id": 2,
                                                "bay_id": 2,
                                                "price_id": 5,
                                                "carnumber": "N414KI",
                                                "startsession": "2021-10-22 11:39:44",
                                                "endsession": "2021-11-16T13:15:03.678097Z",
                                                "occupied": false,
                                                "created_at": null,
                                                "updated_at": "2021-11-16T13:15:03.000000Z"
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "ApiNotFoundException": {
                "properties": {
                    "message": {
                        "description": "The err message",
                        "type": "string",
                        "example": "Car number not found"
                    }
                },
                "type": "object"
            },
            "ApiRequestException": {
                "properties": {
                    "message": {
                        "description": "The err message",
                        "type": "string",
                        "example": "Unauthenticated"
                    }
                },
                "type": "object"
            },
            "BookingResource": {
                "description": "Class BookingResource",
                "properties": {
                    "message": {
                        "title": "message",
                        "description": "message",
                        "format": "string",
                        "default": "Occupied"
                    },
                    "data": {
                        "type": "array",
                        "items": {
                            "properties": {
                                "id": {
                                    "type": "integer",
                                    "example": ""
                                },
                                "bay_id": {
                                    "type": "integer",
                                    "example": ""
                                },
                                "carnumber": {
                                    "type": "string",
                                    "example": ""
                                },
                                "startsession": {
                                    "type": "datetime",
                                    "example": ""
                                },
                                "endsession": {
                                    "type": "datetime",
                                    "example": ""
                                },
                                "price_id": {
                                    "type": "float",
                                    "example": ""
                                },
                                "created_at": {
                                    "type": "datetime",
                                    "example": ""
                                },
                                "updated_at": {
                                    "type": "datetime",
                                    "example": ""
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "id": 1,
                            "bay_id": 1,
                            "carnumber": "L181KL",
                            "startsession": "2021-10-22 11:39:44",
                            "endsession": "2021-10-22 11:39:44",
                            "updated_at": "2021-11-16T06:56:38.000000Z",
                            "created_at": "2021-11-16T06:56:38.000000Z",
                            "price_id": 1
                        }
                    }
                },
                "type": "object"
            },
            "BookingViewResource": {
                "description": "Class BookingViewResource",
                "properties": {
                    "data": {
                        "type": "array",
                        "items": {
                            "properties": {
                                "bayname": {
                                    "type": "string",
                                    "example": ""
                                },
                                "capacity": {
                                    "type": "number",
                                    "example": ""
                                },
                                "carnumber": {
                                    "type": "string",
                                    "example": ""
                                },
                                "startsession": {
                                    "type": "datetime",
                                    "example": ""
                                },
                                "endsession": {
                                    "type": "datetime",
                                    "example": ""
                                },
                                "occupied": {
                                    "type": "boolean",
                                    "example": ""
                                },
                                "price": {
                                    "type": "float",
                                    "example": ""
                                }
                            },
                            "type": "object"
                        },
                        "example": [
                            {
                                "bayname": "A",
                                "capacity": 1,
                                "carnumber": "L181KL",
                                "startsession": "2021-10-22 11:39:44",
                                "endsession": "2021-10-22 11:39:44",
                                "occupied": true,
                                "price": "0"
                            },
                            {
                                "bayname": "",
                                "capacity": 0,
                                "carnumber": "",
                                "startsession": "",
                                "endsession": "",
                                "occupied": true,
                                "price": ""
                            }
                        ]
                    },
                    "message": {
                        "title": "message",
                        "description": "message",
                        "format": "string",
                        "default": "List booking successful"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "Bearer": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header",
                "scheme": "Bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Booking",
            "description": "Authorize required"
        }
    ],
    "security": [
        []
    ]
}